### ISSUE TITLE
css中的position、display、float的小实验

### ISSUE THREAD

**Issue by yooocen** [yooocen/dadaLearningBlogs#5]
# css中的position、display、float的小实验

## 简单的demo
我们先写一个div，里面包着三个小的div，代码如下
```html
<div id="hello">
    <div className="p1">第一</div>
    <div className="p2">第二</div>
    <div className="p3">第三</div>
</div>

```
下面是css样式,需要一些less的语法知识
```less
@charset "utf-8";
.father {
    font-size: 20px;
    width: 400px;
    height: 400px;
    background-color: gray;
}
.son {
    width: 100px;
    height: 100px;
    border: 1px;
    border-style: solid;
    text-align: center;
}

#hello {
    .father;
    .p1 {
        .son;
    }
    .p2 {
        .son;
    }
    .p3 {
        .son;
    }
}
```

效果就是下图所所示
![](rescource/1508057050075.jpg)

## 疑惑1：为什么设置了宽高，三个div却没有并排
这个是因为div是块元素，虽然给块元素设置了宽高，甚至把右外边距设置为0都好，块元素仍然会把它的右外边距填充满它的父亲级元素，可以用chrome的审查元素去看，就是下图所示
![](rescource/WX20171015-165811@2x.png)
橙色部分就是外边距，尽管已经设置为0，但是仍然填充满了
